name: Publish Package to npm
on:
  push:
    branches:
      - main
  release:
    types:
      - published
jobs:
  test:
    name: Unit Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 16.x
    steps:
      - uses: actions/checkout@v1
      - name: 'Use Node.js ${{ matrix.node-version }}'
        uses: actions/setup-node@v1
        with:
          node-version: '${{ matrix.node-version }}'
          cache: yarn
      - name: Install dependencies
        run: yarn
      - name: Run test
        run: yarn test
  build:
    name: Building Package
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '${{ matrix.node-version }}'
          cache: yarn
      - name: Install dependencies
        run: yarn
      - name: Run Build
        run: yarn build
  publish:
    name: Publish Package
    runs-on: ubuntu-latest
    needs:
      - test
      - build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '${{ matrix.node-version }}'
          cache: yarn
      - name: Install dependencies
        run: yarn
      - name: Run Publish
        run: npm publish
        env:
          NPM_TOKEN: '${{ secrets.NPM_TOKEN }}'
